Repository future-architect/go-exceltesting, pull requests merged in 2022-10, with the labels that each got.

#31 Add go-releaser
  .gitignore
  .goreleaser.yaml
Labels: enhancement

#34 Fix cli launch bug
  .goreleaser.yaml
  README.md
  cli/main.go
  docs/compare.md
  docs/dump.md
  docs/example.xlsx
  docs/image/insert_data.drawio.png
  docs/image/insert_definition.drawio.png
  docs/image/overview.drawio.png
  docs/insert.md
Labels: bug

#35 Add description for cli command
  README.md
  out.xlsx
Labels: documentation

#40 fix #38 Add version command
  cli/main.go
Labels: enhancement

#41 #33 dump with existed database record
  cli/dump.go
  cli/dump_test.go
Labels: enhancement

#43 #36 support sheet format version2
  exceltesting.go
  exceltesting_test.go
  testdata/compare_v2.xlsx
  testdata/load_v2.xlsx
Labels: enhancement

#46 パーティションテーブル対応
  compare.xlsx
  exceltesting_test.go
  query.go
  testdata/schema/ddl.sql
Labels: enhancement
